username, title, content, status = 'Ovodov AV','Studying at SkillPlace','Variables','Active'
created_date='10-01-2025'
issue_date='01-10-2025'
print('Имя пользователя:',username,end=';\n')
print('Заголовок заметки:', title,end=';\n')
print('Описание заметки:',content,end=';\n')
print('Статус заметки:',status,end=';\n')
print('Дата создания:',created_date,end=';\n')
print('Дата истечения:',issue_date,end='.')
